name: linter

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

env:
  TERM: "xterm"
  FORCE_COLOR: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    container: nedrey/dpdk-rockylinux8:v21.11-go1.19-snf
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Linter Mandatory
        shell: 'script -q -e -c "bash {0}"'
        run: |
          # don't check unit tests and sample apps
          golangci-lint run --timeout 5m --skip-files=".*_test.go" --skip-dirs="^app"
      -
        name: Linter
        shell: 'script -q -e -c "bash {0}"'
        run: |
          golangci-lint run --timeout 5m --issues-exit-code 0

